Ch-http-status-codes-165996945
TheMottoRw/quickcredit pull request #53
Opened 2019-05-14 14:14 UTC by TheMottoRw

###What this PR do?
###Add and update appropriate HTTP Status codes 
**Signup**
-When user signup return 201 User created
-When user signup with email exist 409 Conflict
**Signin**
-Signin with invalid credential Return 404 not found
-Trying to signin with unverified account return 403 Forbidden
**Apply for a loan**
-Already has loan return status of 409 conflict
-loan applied succesfull return 201 Created
####Story
165996945
###Screenshot
![created](https://user-images.githubusercontent.com/29350976/57704988-469c5080-7663-11e9-9564-16f5f3548c97.PNG)
![Forbidden](https://user-images.githubusercontent.com/29350976/57704989-469c5080-7663-11e9-9856-ebeebf1267ee.PNG)
![Not verified](https://user-images.githubusercontent.com/29350976/57704991-4734e700-7663-11e9-88c2-756d2ca90bb1.PNG)

2019-05-14 16:58 UTC, meshack-mbuvi requested changes

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Loans.js
> +    const loanid = req.params.id;
You can use object destructing here by having:
`const { id } = req.params`

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Loans.js
> +        status: 200,
What did we agree about status codes when a record is not found in the system?

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Loans.js
> +          message: 'no data found',
This message can be made more descriptive enough, for example, `Loan record with the given id is not found`

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Loans.js
> +        message: 'Bad request, there might be some missing parameters',
This message is not descriptive enough, you can have it like `Amount and tenor must be provided`.

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Loans.js
> +          message: 'sorry your account not yet verified, wait for a moment',
When you tell the user to wait for a moment if their account is not verified, are verifying in the background??? I thought you should tell them to either contact an admin for help or access the endpoint for verifying the account.

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Loans.js
> +  const loanParam = req.params;
Since you are only looking for the `id` here, I think you should destructure it `const { id } = req.params` or `const { params : { id } } = req` and then wherever you have `loanParam` use the `id`

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Loans.js
> +  const parameters = req.query;
See the above comments for object destructuring.

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Repayments.js
> +  if (repayParam.id === undefined) {
Same case as above for `repayParam.id`

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Repayments.js
> +  res.status(response.status).json(response);
Ensure you have a black line at the end of every file

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Users.js
> +  const user = req.body;
This could be `const { body : { user } } = req`

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Users.js
> +        error: 'Bad request,all information are required',
This message is not very descriptive

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Users.js
> +    quickcredit.users.push(user);
No need for the comment since everyone knows that you are adding the user to the list. Ideally, you should avoid using comments in your code unless the code is not descriptive enough.

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Users.js
> +        error: 'Bad request,might be some missing paramaters',
same as above on this message

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Users.js
> +          message: 'No data found, wrong username or password',
This message should just be ` Wrong username or password`

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Users.js
> +      // login response specifications
No need for this comment

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Users.js
> +  // getting user information from email
same here

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Users.js
> +  const userEmail = req.params.email;
Use object destructing here

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Users.js
> +          message: `No data related to ${userEmail} found`,
The message is not descriptive

2019-05-14 16:58 UTC, meshack-mbuvi commented on server/controllers/Users.js
> +    // updating account based on account index
Comments not needed here

2019-05-14 17:18 UTC, TheMottoRw commented on server/controllers/Users.js
> +    // updating account based on account index
Thanks for the feedback i am going to work on it line to line,may hope tomorrow afternoon all will be resolved

2019-05-16 14:27 UTC, meshack-mbuvi requested changes

2019-05-16 14:27 UTC, meshack-mbuvi commented on server/controllers/Loans.js
> +};
New line after every `export const ...`

2019-05-16 14:27 UTC, meshack-mbuvi commented on server/controllers/Repayments.js
> +        message: 'amount must be provided',
This message should be `Amount must be provided`

2019-05-16 14:27 UTC, meshack-mbuvi commented on server/controllers/Repayments.js
> +          message: `amount paid does not match to installement payment paid ${amount} installement payment must be ${loanInfo.paymentInstallement}`,
Start every sentence with a capital letter.

2019-05-16 14:27 UTC, meshack-mbuvi commented on server/test/test.js
> +});
Add a blank line after every `describe(..)`

2019-05-16 17:22 UTC, meshack-mbuvi approved these changes

2019-05-16 17:23 UTC, meshack-mbuvi requested changes
Resolve merge conflicts

2019-05-16 22:03 UTC, merged